### PR TITLE
Add azure webhooks doc

### PR DESCRIPTION
**Pull request by raulcabello**
related to https://github.com/rancher/fleet/issues/1998

### CODE REVIEW

**Review by weyfonk — APPROVED** [review]
LGTM :)

**Comment by weyfonk** [comment]
Do we want this added to 0.9 and 0.8 docs as well?

**Comment by raulcabello** [comment]
> Do we want this added to 0.9 and 0.8 docs as well?

yes, but I guess we will need to wait for the new releases. What do you think?

**Comment by weyfonk** [comment]
> > Do we want this added to 0.9 and 0.8 docs as well?
> 
> yes, but I guess we will need to wait for the new releases. What do you think?

Agreed, it makes more sense to wait for new 0.8 and 0.9 releases.

**Pull request merged**
